spring:
  application:
    name: local-api
  datasource:
    url: jdbc:sqlite:${app.runtime.root}/local-api/local-api.db
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: never

app:
  core:
    clash-meta:
      path: ${APP_CORE_CLASH_META_PATH:}
  runtime:
    root: ${APP_RUNTIME_ROOT:./.runtime}
  session:
    token: ${APP_SESSION_TOKEN:dev-session-token}

server:
  port: 0
  address: 127.0.0.1
