SET NAMES utf8mb4;

USE drug_management;

CREATE TABLE IF NOT EXISTS user_account (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL UNIQUE,
  user_name VARCHAR(64) NOT NULL,
  role VARCHAR(32) NOT NULL,
  password VARCHAR(128) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS drug (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  drug_code VARCHAR(64) NOT NULL UNIQUE,
  drug_name VARCHAR(128) NOT NULL,
  generic_name VARCHAR(128),
  category VARCHAR(64),
  specification VARCHAR(128),
  unit VARCHAR(32) NOT NULL,
  manufacturer VARCHAR(128),
  approval_number VARCHAR(128),
  purchase_price DECIMAL(10,2) NOT NULL,
  sale_price DECIMAL(10,2) NOT NULL,
  low_stock_threshold INT NOT NULL DEFAULT 0,
  enabled TINYINT NOT NULL DEFAULT 1,
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  drug_id BIGINT NOT NULL,
  batch_no VARCHAR(64) NOT NULL,
  expiry_date DATE NOT NULL,
  quantity INT NOT NULL DEFAULT 0,
  locked_quantity INT NOT NULL DEFAULT 0,
  location_code VARCHAR(64),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_inventory_batch (drug_id, batch_no, expiry_date)
);

CREATE TABLE IF NOT EXISTS inventory_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  drug_id BIGINT NOT NULL,
  inventory_id BIGINT NOT NULL,
  record_type VARCHAR(32) NOT NULL,
  quantity_change INT NOT NULL,
  before_quantity INT NOT NULL,
  after_quantity INT NOT NULL,
  biz_no VARCHAR(64),
  operator_name VARCHAR(64),
  operated_at DATETIME NOT NULL,
  remark VARCHAR(255),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prescription (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  prescription_no VARCHAR(64) NOT NULL UNIQUE,
  patient_name VARCHAR(128) NOT NULL,
  created_by_user_id BIGINT NOT NULL,
  created_by_role VARCHAR(32) NOT NULL,
  doctor_id BIGINT NOT NULL,
  doctor_name VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  doctor_approval_status VARCHAR(32) NOT NULL,
  doctor_approved_at DATETIME,
  pharmacist_operator_id BIGINT,
  audit_by VARCHAR(64),
  audit_time DATETIME,
  dispense_by VARCHAR(64),
  dispense_time DATETIME,
  reject_reason VARCHAR(255),
  remark VARCHAR(255),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prescription_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  prescription_id BIGINT NOT NULL,
  drug_id BIGINT NOT NULL,
  dosage VARCHAR(64),
  frequency VARCHAR(64),
  days INT NOT NULL,
  quantity INT NOT NULL,
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS warning_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  warning_type VARCHAR(32) NOT NULL,
  drug_id BIGINT,
  inventory_id BIGINT,
  content VARCHAR(255),
  status VARCHAR(32),
  remark VARCHAR(255),
  created_by VARCHAR(64),
  updated_by VARCHAR(64),
  deleted TINYINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
